services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=iot_data
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - iot-network
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf-agent
    environment:
      - TELEGRAF_CONFIG_PATH=/etc/telegraf/telegraf.conf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro,Z
    depends_on:
      - timescaledb
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    external: true

volumes:
  timescale_data:
